language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:coveralls
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: <your api key>
  app: <your app name>
  skip_cleanup: true
notification:
  email: false
  